### PR TITLE
FIX: follow-up to #964; subscribe-after-init

### LINKED ISSUE #978: EpicsSignalEditMD still has initialization (?) issues (wrt `.log`)
## Behavior
`EpicsSignalEditMD` can throw these errors in typhos:

```python
Traceback (most recent call last):
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/ophyd/ophydobj.py", line 462, in inner
    cb(*args, **kwargs)
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/pcdsdevices/signal.py", line 979, in _enum_string_updated
    self.log.debug(
AttributeError: 'EpicsSignalEditMD' object has no attribute 'log'
```

Related to my changes in #963 assuredly

Ripple effect from the full traceback here:
<details>

```python
[2022-03-24 09:23:22,347] [ERROR   ] - Subscription value callback exception (PytmcSignalRO(read_pv='PF1K0:WFS:MMS:STATE:06:NAME_RBV', name='pf1k0_target_config_state06_state_name', parent='pf1k0_target_config_state06', value='TARGET5', timestamp=1648139001.923994, auto_monitor=False, string=True))
Traceback (most recent call last):
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/ophyd/device.py", line 223, in __get__
    return instance._signals[self.attr]
KeyError: 'target'
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/ophyd/device.py", line 223, in __get__
    return instance._signals[self.attr]
KeyError: 'state'
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/ophyd/ophydobj.py", line 462, in inner
    cb(*args, **kwargs)
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/pcdsdevices/signal.py", line 979, in _enum_string_updated
    self.log.debug(
AttributeError: 'EpicsSignalEditMD' object has no attribute 'log'
```
</details>

## Possible Solution
Ensure `.log` and other vital attributes are appropriately setup

## Steps to Reproduce (for bugs)
Load `kfe` screens

## Context
Mike E showed these tracebacks in his terminal while debugging a typhos issue

## Your Environment
pcds-dev

### PR DESCRIPTION
**Pull request by klauer**
## Description
`EpicsSignalBaseEditMD` and related classes can have initialization problems as in #978 and #963.

## Motivation and Context
* Intending to close #978 
* Supersedes my failed fix in #964 
* I'm hoping to come up with a good fix the 2nd time around so a 3rd time around isn't necessary.

## How Has This Been Tested?

* Test suite
* Loaded up LFE screen as in the issue and didn't notice a traceback
* Current `lfe` still shows log-related error messages

## Where Has This Been Documented?
* PR and issue text

## Pre-merge checklist
- [x] Code works interactively
- [x] Code contains descriptive docstrings, including context and API
- [x] New/changed functions and methods are covered in the test suite where possible
- [x] Test suite passes locally
- [x] Test suite passes on travis
- [x] Ran docs/pre-release-notes.sh and created a pre-release documentation page
- [x] Pre-release docs include context, functional descriptions, and contributors as appropriate

### CODE REVIEW

**Comment by klauer** [comment]
I think this is arguably a _better_ fix than the previous one. It would benefit from a second set of eyes on it, for sure.

**Comment by tangkong** [comment]
I was poking around with this earlier and actually saw the traceback regardless of of whether or not I reverted recent changes.  I still seem to see the `.log` traceback if I load `kfe` though.  If I try `lfe` and it hangs for a while, it'll also show the traceback.  

I dunno if it's just a me-and-my-machine thing, but the timing is truly finicky

**Comment by klauer** [comment]
I think the timing shouldn't be too difficult to understand when taking into account the following:
* A `.subscribe()` call can immediately result in a callback
* If a `.subscribe()` call is used in `__init__`, it must be done _after_ everything is setup
    * This includes the `super().__init__()` call, specifically for setting up `OphydObj` stuff like `.log`
    * This includes the subclass-specific implementation details (such as the enum value/metadata override stuff here)

The original fix worked for one scenario but not all. I think this could (or should) work for all if my assumptions are correct.

**Comment by ZLLentz** [comment]
Gotcha, I understand at a surface-level now. If you observe this reducing the number of errors I say we go for it and merge.

In general, should we advise against creating EPICS subscriptions on init? Does this sort of thing have startup costs when e.g. the PVs are disconnected? Those are the main things I'm worried about for other devices.

**Comment by klauer** [comment]
> In general, should we advise against creating EPICS subscriptions on init? Does this sort of thing have startup costs when e.g. the PVs are disconnected? Those are the main things I'm worried about for other devices.

I don't think there is a blocking effect any longer when the PV is disconnected, though that may have been the case at some point.
As to race conditions at `__init__` time, we should be extremely careful and follow the "at the true tail-end of `__init__`" thing I mentioned above

**Review by ZLLentz — APPROVED** [review]
Let's merge this then, if the observed failures were just test environment interference
